[package]
name = "sudoku-rs"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
rand = "0.6"

[dev-dependencies]
proptest = "0.9.0"
rand_xorshift = "0.1.1"
